# Generated by Django 4.2.1 on 2023-06-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_report_delete_problem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='solutions/')),
                ('problem', models.CharField(max_length=255, null=True)),
                ('chances', models.CharField(max_length=255, null=True)),
                ('precautions', models.TextField(null=True)),
                ('solutions', models.TextField(null=True)),
                ('advisor', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
